# Extensions to be sourced by ~/.bashrc

. ~/.config/nvim/bash/cmds

# Configure colors, if available.
if [ `which tput` ] && tput setaf 1 >&/dev/null; then
    c_reset='\[\e[0m\]'
    c_user='\[\033[1;33m\]'
    c_path='\[\e[0;33m\]'
    c_git_clean='\[\e[0;36m\]'
    c_git_dirty='\[\e[0;35m\]'
else
    c_reset=
    c_user=
    c_path=
    c_git_clean=
    c_git_dirty=
fi

# Function to assemble the Git part of our prompt.
git_prompt ()
{
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        return 0
    fi

    git_branch=$(git branch 2>/dev/null| sed -n '/^\*/s/^\* //p')

    if git diff --quiet 2>/dev/null >&2; then
        git_color="$c_git_clean"
    else
        git_color="$c_git_dirty"
    fi

    echo " [$git_color$git_branch${c_reset}]"
}

dev()
{
    if [ "$1" == "up" ]; then
        if [ -n "${2+x}" ] && [ "$2" = "rm" ] ; then
            remove="--remove-existing-container"
        elif [ -n "${2+x}" ] && [ "$2" = "rmnc" ] ; then
            remove="--remove-existing-container --build-no-cache"
        else
            remove=
        fi
        username=$(devcontainer read-configuration --workspace-folder . 2>/dev/null | jq -r '.configuration.remoteUser // "vscode"')
        devcontainer "$1" \
            --mount type=bind,source=/nix,target=/nix \
            --mount type=bind,source=/tmp,target=/tmp \
            --mount type=bind,source="$HOME"/.config/nvim,target=/home/"${username}"/.config/nvim \
            --mount type=bind,source="$HOME"/.local,target=/home/"${username}"/.tools \
            --mount type=bind,source="$HOME"/.gitconfig,target="$HOME"/.gitconfig \
            --mount type=bind,source="$SSH_AUTH_SOCK",target="$SSH_AUTH_SOCK" \
            --mount type=bind,source="$HOME"/.config/nvim/bash/50-nvim.sh,target=/etc/profile.d/50-nvim.sh \
            --mount type=bind,source="$HOME"/.config/helix,target=/home/"${username}"/.config/helix \
            --mount type=bind,source=/etc/ssl/certs/ca-certificates.crt,target=/etc/ssl/certs/ca-certificates.crt \
            --mount type=bind,source="$HOME"/.cache/bazel,target=/home/"${username}"/.cache/bazel \
            --mount type=bind,source="$PWD"/..,target=/workspaces \
            --remote-env REQUESTS_CA_BUNDLE="$REQUESTS_CA_BUNDLE" \
            $remove --workspace-folder .
    else
        devcontainer exec \
	    --remote-env SSH_AUTH_SOCK="$SSH_AUTH_SOCK" \
	    --remote-env TZ=UTC \
        --remote-env DISPLAY="$DISPLAY" \
        --remote-env VECTOR_LICENSE_FILE="$VECTOR_LICENSE_FILE" \
        --remote-env REQUESTS_CA_BUNDLE="$REQUESTS_CA_BUNDLE" \
        --remote-env PLANTUML_SERVER="$PLANTUML_SERVER" \
        --remote-env RAI_LLM_URL="$RAI_LLM_URL" \
        --remote-env RAI_LLM_API_TOKEN="$RAI_LLM_API_TOKEN" \
        --remote-env RAI_LLM_MODEL="$RAI_LLM_MODEL" \
        --remote-env HANDLER="$HANDLER" \
        --remote-env OPENAI_ENDPOINT="$RAI_LLM_URL" \
        --remote-env OPENAI_API_KEY="$RAI_LLM_API_TOKEN" \
        --remote-env OPENAI_MODEL="$RAI_LLM_MODEL" \
	    --workspace-folder . "$@"
    fi
}

excali()
{
    res=$(docker ps -q --filter="name=excalidraw")
    if [ "$res" = "" ]; then
        docker run --rm -dit --name excalidraw -p 5000:80 excalidraw/excalidraw:latest
    fi
    wslview http://localhost:5000
}

# Thy holy prompt.
PROMPT_COMMAND='PS1="${c_user}\u${c_reset}@${c_user}\h${c_reset}:${c_path}\W${c_reset}$(git_prompt)\$ "'

alias gis='git status'

if [ -n "$WSL_DISTRO_NAME" ]; then
    # Required for WSL2 to avoid some error messages
    sudo mount --make-rshared /
fi

alias sudo='sudo '
if [ -z ${NVIM+x} ]; then
  alias vim=nvim
else
  alias vim='nvim --server $NVIM --remote'
fi
export EDITOR=hx
export VISUAL=hx

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
# To make devcontainer features work.
# See https://github.com/microsoft/vscode-remote-release/issues/6092#issuecomment-1593704882
export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
ssh-add -l 2>/dev/null >/dev/null
if [ $? -ge 2 ]; then
    rm "$SSH_AUTH_SOCK" 2>/dev/null >/dev/null
    ssh-agent -a "$SSH_AUTH_SOCK" 2>/dev/null >/dev/null
    ssh-add
fi
export BASH_ENV=~/.config/nvim/bash/bashrc
