#!/bin/bash

dirdiff()
{
    # Shell-escape each path:
    DIR1=$(printf '%q' "$1"); shift
    DIR2=$(printf '%q' "$1"); shift
    nvim $@ -c "DirDiff $DIR1 $DIR2"
}

mrc()
{
    local branch_name
    branch_name=$(git branch --show-current)
    git remote update && \
    git co main && \
    git pull && \
    git branch -d "${branch_name}" && \
    git remote prune origin
}

